dlang/dub-registry

- source/app.d
- source/dubregistry/api.d
- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
- source/dubregistry/web.d
The idea is that this should allow us to start adding badges to [shields.io](http://shields.io/).
This PR also leads the way towards adding more stats in the future.
> Added API framework and a package stats endpoint

- views/package_format.dt
- mention that it copies directories as well
- give an example for matching a dir vs. files in a dir
> update documentation of copyFiles

- source/dubregistry/registry.d
- source/dubregistry/repositories/bitbucket.d
- source/dubregistry/repositories/github.d
- source/dubregistry/repositories/repository.d
- source/dubregistry/web.d
- views/my_packages.register.dt
- views/my_packages.register.warn_fork.dt
It happened now a couple of times (e.g. to @adamdruppe and @Hackerpilot) that someone forked a popular repository to register it on code.dlang.org. Later, the original authors tried to do the same, discovering that the name is already taken. To make people aware of this issue, this now adds a warning whenever a forked repository is detected.
> Add warning when registering a fork

- public/styles/top_p.css
- views/layout.dt
(follow-up to #141)
> The top bar should have its contents aligned with the main contents. The logo in particular should start at the same column as the text below. 
Done.
> The search button should just have the word "Go" dropped, the loupe is enough and also too close to the "Go" ATM.
I didn't update the alpha server after @MartinNowak PR - it was just "Go". This PR replaces the word "Go" back to the loupe.
@s-ludwig Anything else that's blocking the new design?
(Changes are uploaded to alpha.dub.pm again - we might want to create some CI at some point)
> Redesign part 2

- public/styles/top_p.css
- for screens above 66em (where we fold the search box) and below
~1100px the menu entries wrap to another line
- somewhat normal format for a 24" vertical screen
- fixed by reducing the extra wide search field
before
after
> fix menu wrap on narrow screens

- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
- native/indexed db support for searching
- supports full search syntax of MongoDB, i.e.
`multiple words`, `"phrase search"`, `word -exclusion`
- higher weights for name and description
- stemming of search terms (uses english by default, can be overriden on
a per package base, by adding a language field)
- ignores stopwords
- does not perform proximity search (typos), but our
levenshtein search returned a lot of nonsense
- can't currently index the readme b/c it's not in the db, so people
will have to optimize their short description to be nicely searchable
- don't index categories which should be an orthogonal search filter
> use MongoDB full text search

- public/styles/top_p.css
This makes the site look consistent with main dlang.org site
and also much more readable.
> Use normal font-weight.

- public/styles/top.css
_justify_ looks bad for several packages:
> align package description text to the left

- source/app.d
- source/dubregistry/dbcontroller.d
- source/dubregistry/mirror.d
- source/dubregistry/registry.d
- source/dubregistry/web.d
- views/docs.commandline.dt
- views/download.dt
- views/home.dt
- views/layout.dt
- views/layout.inc.menu.dt
- views/view_package.dt
Can be enabled with `./dub-registry --mirror https://code.dlang.org/`
The most obvious improvement will be to add an API endpoint to receive a complete database dump instead of querying each package individually.
> Implement a simple registry mirror mode

- source/dubregistry/api.d
- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
This fetches the whole package database in a single request. The response is forced to be GZIP compressed to avoid excessive bandwidth use (currently 20MB uncompressed for ~1000 packages, 1.3MB compressed).
> Add an /api/packages/dump REST API endpoint.

- source/dubregistry/cache.d
- source/dubregistry/notificationcenter.d
Fixes:
```
source/dubregistry/cache.d(83,25): Deprecation: constructor vibe.stream.memory.MemoryStream.this is deprecated - Use createMemoryStream instead.
source/dubregistry/cache.d(106,17): Deprecation: constructor vibe.stream.memory.MemoryStream.this is deprecated - Use createMemoryStream instead.
source/dubregistry/cache.d(127,20): Deprecation: constructor vibe.stream.memory.MemoryOutputStream.this is deprecated - Use createMemoryOutputStream isntead.
source/dubregistry/cache.d(128,18): Deprecation: function vibe.core.stream.OutputStream.write is deprecated - Use pipe(source, sink) instead.
source/dubregistry/cache.d(133,18): Deprecation: constructor vibe.stream.memory.MemoryStream.this is deprecated - Use createMemoryStream instead.
source/dubregistry/notificationcenter.d(54,14): …
```
> Fixing deprecated warnings

- views/my_packages.package.dt
Looks like this:
It works only on 'Edit package' page which means only package owners can see it. I don't want to add this to main package page `'view_package.dt'` yet, because it looks ugly.
Implements #169 (at least partially).
> Display download statistics on 'Edit package' page

- source/dubregistry/dbcontroller.d
- source/dubregistry/mirror.d
- source/dubregistry/registry.d
It was possible that a package in the local database had a different ID than the one from the source registry. This caused the update to fail due to a name conflict. With this change, the entry with the mismatching ID is now removed first.
> Let mirror mode remove packages by ID to avoid name conflicts.

- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
- source/dubregistry/repositories/bitbucket.d
- source/dubregistry/repositories/github.d
- source/dubregistry/repositories/repository.d
- source/dubregistry/web.d
The final goal is to eliminate all uses of `Json` except for package recipe contents.
> Use a static type for repository identifiers.

- source/dubregistry/api.d
- source/dubregistry/registry.d
- source/dubregistry/viewutils.d
- source/dubregistry/web.d
- views/home.dt
- views/my_packages.dt
- views/my_packages.package.dt
This makes another step into the direction of working only with static types. In particular, this also fixes the issue of accessing the non-existent JSON field "url" (removed after deprecation period), which didn't get caught because it was read from a dynamic 'Json' value.
> Let getPackageInfo return a static type and fix access to "url".

- public/styles/common.css
- source/dubregistry/web.d
- views/home.dt
- views/view_package.dt
- views/view_package.versions.dt
I wanted to add some usefull little things like download statistics or stars, but realised that there is no place where I can put them.
So, I did this:
All package information moved to sidebar at right of the screen. On the small screens (<54em) it showed at the bottom of page. Package name, description, installation instructions and readme stays at left of the screen.
Also, sidebar is grey(gray?) and contains a lot of empty space, so it won't look heavy.
Anyway, it's not done yet
> New layout of package page

- public/styles/common.css
- views/my_packages.register.dt
This PR changes layout of the 'Add package' page. I wanted to make it mobile-friendly and clear.
> New layout of 'Add package' page

- views/userman.forgot_login.dt
Changes layout of the 'reset password' page
Screenshots:
> New layout of the 'reset password' page

- views/my_packages.package.dt
- views/view_package.dt
They put a huge strain on the production database server and make the site unusable in certain parts. Once #224 is merged, this can be re-enabled.
> Temporarily disable download statistics.

- source/dubregistry/web.d
- views/advanced_usage.dt
- views/getting_started.dt
- views/layout.inc.menu.dt
This is a complete rewrite of the getting started guide (which has become a full "How to use DUB" reference and included items not important to someone just getting started). An "Advanced Usage" (or something similar) page should likely be created as well; if desired I could make that part of this PR, or could make another.
I completely removed:
* "Building foreign projects" - the documentation is incorrect (dub fetch isn't supported) and not particularly useful here.
* The suggested project layout. I do show the generated minimal layout.
* The single-file package documentation. This would be a better fit for an advanced usage section. I do not see this documented anywhere else.
* The local package documentation. This would also be a better fit for an advanced usage section. This is …
> Rewrite Getting Started guide.

- public/styles/common.css
Fixes this:
Works for all input forms with `.inputForm` class.
> Fix labels issue in Firefox

- public/styles/common.css
- views/view_package.dt
- use definition list for named sections and add a bit of spacing
- align all entries to 0.5em padding
> improve styling for package info

- public/styles/common.css
Makes "Remove this package" button smaller and paints it red, as intended in #245.
> Fix "Remove this package" button

- views/download.dt
When @dicebot stepped down as the package maintainer, the community packages were dropped and replaced by an AUR package.
> [trivial] Fix the information about Arch Linux packages.

- source/dubregistry/internal/workqueue.d
- source/dubregistry/registry.d
While the update queue is mostly API performance dependent, the statistics updates are mostly DB query performance dependent. Computing them in sequence resulted in a serious decline in package update check performance. With this change, statistics updates should have almost no impact on the update speed. If they turn out to be slower than the updates, they will simply be updated as fast as possible in a round-robin fashion.
> Compute statistics updates in a queue parallel to the general update queue.

- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
- source/dubregistry/viewutils.d
- source/dubregistry/web.d
- views/home.dt
- views/search_results.dt
- views/view_package.dt
- compute ranking between 0 and 5
- show ranking only with `?showranking` query parameter for now
- more stat details visible on hover (better visualization/explanation pending)
- sort search results by relevance (rounded ranking and [FTS score](https://docs.mongodb.com/manual/reference/operator/query/text/#text-operator-text-score))
Commits are properly structured and should be reviewed one-by-one.
**Note for deployment:** it will take a full update cycle to populate the package stats with real data. Only on the 2nd update round (after ~30min.) we can compute the stat distributions and ratings. So initially all packages will show as equally zero rated which behaves like the status quo ;).
> package rank story

- source/dubregistry/web.d
If the url is `#foobar` (an anchor link), the blob file should be `README.md`
> Fix anchor link in README.md when viewing package info

- public/styles/common.css
In particular makes the update section look like this instead of having a green button:
> [trivial] Style disabled buttons gray and with no "hand" mouse cursor.

- views/package_format_json.dt
- views/package_format_sdl.dt
The documentation didn't mention that pkg-config is used on Posix platforms to resolve linker flags for libraries specified in the "libs" field of the package config file
> Mention dub using pkg-config in the package file format documentations

- public/styles/common.css
- views/home.dt
Added Per Page option
Limit should stay when changing categories
Added function to generate home url instead of copy pasting
> Reapply PR #209, which got accidentally reverted in #203 previously.

- views/view_package.dt
When viewing a subpackage the "Manage this package" link redirects to `my_packages/package:subpackage` instead of `my_packages/package`.
> Fix wrong link to my_packages from subpackage

- public/styles/common.css
Don't set the background color without setting the foreground color. For dark themes the text could be white by default.
> Specify foreground color for inputs

- dub.selections.json
Required for running the registry locally.
See also e.g.
https://github.com/dlang/dub-registry/issues/285
> Bump dependencies to vibe 0.8.3-beta.1

- dub.sdl
I haven't been doing any noteworthy thing for dub-registry, hence removing myself from the 'Authors' section.
> Remove mdondorff from authors

- source/dubregistry/repositories/gitlab.d
When authorization was used, the URL used by download() was invalid, because getDownloadURL() returned null in this case. This was a regression introduced in 54c4a524f5995d0c5149baa42facab3d6731a166.
> Fix forwarded download of GitLab hosted packages.

- netlify.sh
- netlify.toml
Looks like this approach is going to work :)
Their docker container is a bit limited, but no problem - we can download all binaries we need.
For now this just makes the a few pages visible.
Next steps:
- use the mirror mode to fetch all packages.
- find a workaround against filenames containing '?' (netlify doesn't support these)
BTW we could netlify too also deploy all the documentation pages to dub.pm directly from this repo (though we still might put them in a separate repo or sub-repo, s.t. the builds are faster here)
> Use netlify for previewing PRs

- public/styles/common.css
- source/dubregistry/dbcontroller.d
- source/dubregistry/web.d
- views/my_packages.register.dt
When creating a package and pasting a URL or repository creator + name it fills out the information automatically now.
Accepted formats:
```
dlang/dub
http(s)://(www.)github.com/dlang/dub
http(s)://(www.)gitlab.com/foo/bar
http(s)://(www.)bitbucket.org/foo/bar
```
> Package creation input convenience

- netlify.sh
- source/app.d
- source/dubregistry/mirror.d
As mentioned in https://github.com/dlang/dub-registry/pull/307, downloading the Json doesn't work (or well it takes 10 minutes), so I made `--mirror` support importing a manually downloaded copy of the Json file.
This is also handy for my local development, when I want to quickly nuke the entire database and on my machine `--mirror=...` doesn't work well either (could be due to my crappy internet though).
>  Improve the netlify preview to show packages

- .gitignore
- .travis.yml
As discussed in https://github.com/dlang/dub-registry/issues/213, this is a first step towards a better test coverage and prevention of regression.
This PR only adds the Travis framework for better testing. It doesn't add more tests and thus won't reproduce the Botan segfault. However, it does add more compilers, which are automatically updated if the script is run regularly (cron daily!) and already compiles everything with "Botan" selected.
Once this is green & merged, the next obvious step is to actually add a couple of real tests, but this is the first and simple step towards this goal.
> Improve Travis setup: add ldc + botan

- source/dubregistry/dbcontroller.d
- source/dubregistry/internal/utils.d
- source/dubregistry/registry.d
- source/dubregistry/web.d
This removes a source of high memory use (~80MB) and also a source for what appears as a memory leak. It's not clear what keeps the memory pinned for the old approach, but it showed a steady increase in memory consumption for each package list update.
> Only store data necessary for sorting the package list in memory.

- dub.sdl
before, compilation broke after `dub upgrade` because of
```
source/dubregistry/internal/workqueue.d(59,12): Error: no property putFront for type FixedRingBuffer!(string, 0LU, true), did you mean vibe.utils.array.FixedRingBuffer!(string, 0LU, true).FixedRingBuffer.popFront?
source/dubregistry/internal/workqueue.d(62,3): Warning: statement is not reachable
```
> Update vibe.d dependency to allow build after dub upgrade again

- source/dubregistry/dbcontroller.d
Caused by a representation change of absolute paths between vibe-d:core and vibe-core.
Fixes dlang/dub#1441
> Replace assertion by enforcement to avoid crashing the registry.

- views/view_package.dt
Preview:
(FWIW the dub registry doesn't work well with mongo 3.6 - I had to disable the stats aggregation locally for now.)
> Add <package>.dub.pm shorturls to the package overview

- source/dubregistry/registry.d
- source/dubregistry/web.d
The last ones come from Vibe.d:
```
../../.dub/packages/vibe-d-0.8.4-alpha.1/vibe-d/data/vibe/data/json.d(2514,25): Deprecation: function `std.exception.enforceEx!(JSONException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.
../../.dub/packages/vibe-d-0.8.4-alpha.1/vibe-d/data/vibe/data/json.d(2514,25): Deprecation: function `std.exception.enforceEx!(JSONException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089.
../../.dub/packages/vibe-d-0.8.4-alpha.1/vibe-d/data/vibe/data/json.d(2514,25): Deprecation: function `std.exception.enforceEx!(JSONException).enforceEx!bool.enforceEx` is deprecated - Use enforce. enforceEx will be removed with 2.089. …
```
> [trivial] Fix a few deprecations

- source/dubregistry/dbcontroller.d
- source/dubregistry/registry.d
- source/dubregistry/web.d
- views/my_packages.package.dt
- views/view_package.dt
Allows the user to set the documentation url. By default (aka empty string) it will point to dpldocs.info.
The URL is only verified on a very naive level, but if the user wants to put stupid things in there, it will probably be hard to prevent him from doing so anyhow.
with the html pattern verification disabled:
CC @WebFreak001
> Fix #312 - allow to manually configure the documentation url

- source/dubregistry/registry.d
Happened for packages with zero downloads.
> [trivial] Avoid division by zero when computing the download score.

- source/dubregistry/web.d
The number of items on the first page got erroneously used as the total number of packages, thus always resulting in a single result page.
This got broken with the recent front page update: #303 
Fixes #339
> Use the full package count for pagination

- source/dubregistry/repositories/gitlab.d
(This pull request is work in progress and is not tested yet, I do not have the means of testing if this works currently. But will test soon.)
I expect there to be breaking API changes between version 3 and 4. But I'll test when i get home.
GitLab 11.0 deprecated use of API v3 fully, therefore GitLab support is currently broken. See https://github.com/dlang/dub-registry/issues/342
> Change GitLab API to version 4

- README.md
- source/dubregistry/internal/utils.d
- source/dubregistry/repositories/gitlab.d
from #342 I saw that there were several useless HTTP requests and now the black function also censors query parameters starting with private or secret (fixing that the gitlab access token is dumped to the user)
> Gitlab improvements

- source/app.d
- source/dubregistry/cache.d
Without this, registering new packages fails.
> Use the global databaseName for the Download Cache

- app.json
This simply removes the release mode from Martin's buildpack.
I'm not sure yet on the best way to make this configurable for the users, but when I do I will make an upstream PR to Martin's buildpack.
However, for now this should drastically reduce the build times and provide us with stack traces.
> Use a debug Heroku buildpack for now

- source/dubregistry/web.d
This fixes the deprecation warning:
```
source/dubregistry/web.d(120,10): Deprecation: dubregistry.dbcontroller.tuple is not visible from module web
```
> Add missing import for std.typecons : tuple

- Dockerfile
- README.md
Looks like they changed the Docker image. Better fix it to sth. stable.
Debian 8 is used because the binary is built on Travis which still uses OpenSSL 1.0.0.
> Fix #372 - libssl.so.1.0.0 not found in Docker image

- public/styles/common.css
On some os(eg. gnome shell with dark gtk theme) the default background colours for input boxes is black.
This is a proposal for fixing this issue.
> Update input style

- app.json
- source/app.d
Allows to set the config variables optionally via environment variables (soft fallback)
This is useful for e.g. the Heroku Apps where the app is ephermal and all configuration is done via environment variables, which can be inherited automatically to new review instances.
> Environment fallback for config variables

- source/dubregistry/dbcontroller.d
- source/dubregistry/repositories/gitlab.d
- views/my_packages.register.dt
This pull requests allows to register packages for GitLab projects placed into subgroups.
Currently the problem is that URL validation throws an error, because it expects url like *service*[.com]//*owner*/*project*. However, GitLab's subgroups allow URLs like gitlab.com/*owner*/*subgroup*/*subsubgroup*/*project*.
This pull request renames **m_project** to **m_projectPath** in **GitLabRepository** and allows it to store the *subgroup*/*subsubgroup*/*project* as is with slashes - so the first part after the URL is put into **m_owner** as it was before, but the rest is joined and put into **m_projectPath** even if contains slashes.
The regex is adjusted as well so that multiple slashed parts are allowed.
This will fix #374.
> Support for GitLab projects inside subgroups

- .travis.yml
Workarround for issue #406 . As referred, `botan` looks unmaintained and `openssl` seems used in production.
> Allow botan to fail on travis-ci

- README.md
putting plain text account passwords into webserver text files is stupid
Personal access tokens on github are a low-privilege replacement for the user password for HTTP basic authentication (which is being used)
> Replace readme github password with access token

- views/home.dt
For example, the first 20 packages would be presented as "Displaying results 1 to 21 of 1551 packages found."
> Fix off by one error.

- views/my_packages.register.dt
> fix space in package registration

- source/dubregistry/repositories/gitlab.d
GitLab has updated its API to download the repository archive, so it causes the issue because it could not download the requested repository
Updating the generation of the URL (https://docs.gitlab.com/ee/api/repositories.html#get-file-archive) with the new API is enough to solve the problem
To test: https://salty-hamlet-35363.herokuapp.com/packages/gitlab-test-package/1.0.0.zip
> Fix issue #436 - Update GitLab APIs

- source/dubregistry/dbcontroller.d
Returning the `Nullable!DbPackage`, implicitly converted to `DbPackage`, triggered a codegen issue on LDC, leading to the version string to become empty on Windows and causing a crash on the following method call on Linux.
Closes #436. Fixes #349.
> Work around a stack corruption causing broken GitLab downloads

- source/dubregistry/repositories/bitbucket.d
This fixes a timestamp parsing bug introduced through PR #445. This change seems to work when tested in isolation.
But I claimed the same thing for the original PR...
> Fix bitbucket branch/tag timestamp parsing

- source/dubregistry/repositories/gitlab.d
Currently GitLab support is broken for private repositories.
see: https://gitlab.com/gitlab-org/gitlab-foss/issues/55081
This commit makes dub-registry use GitLab api thus fixing private repository browsing
> Fixed GitLab private repositories download file URL

- README.md
The repository was migrated and the links need to be updated.
> Replace travis-ci link from .org to .com

- source/dubregistry/web.d
I noticed that the "Learn more about publishing" links redirect to the Command Line Usage page on dub.pm, instead of the actual publishing page.
> Fix link to page explaining how to publish

- source/app.d
- source/dubregistry/mirror.d
This mainly allows to run a mirror in a way where the background service only provides the web frontend (and REST API) and database updates happen in separate process invocations (executed by a cron job). Since there is currently a massive memory leak somewhere in the "request package dump -> read compressed answer and uncompress -> deserialize JSON to native representation" process.
This is already deployed on codemirror.dlang.org, so that it's uptime should now also be virtually 100%.
> Mirror improvements

- source/dubregistry/repositories/gitlab.d
The GitLab API started rejecting paths starting with /
https://gitlab.com/gitlab-org/gitlab/-/issues/212216
Fixes https://github.com/dlang/dub-registry/issues/471
> Fix GitLab readFile()

- categories.json
adds a category which can be used to indicate that libraries are written in a WebAssembly compatible way or written for WebAssembly specifically (like Web API wrappers or entire standard library implementations for the web)
Maybe if there are possible standard formats to generate the glue code from D to JS/WASM or define the exports, this category additionally helps with finding these.
> add 'WebAssembly compatible' category

- categories.json
There are currently 38 packages mentioning `-betterC` support in the description, and an unknown number of packages supporting `-betterC` not mentioned in the description. Adding a category for it could make it easier to find them once package maintainers apply it appropriately.
> Add BetterC category

- dub.sdl
- dub.selections.json
- source/app.d
- source/dubregistry/registry.d
There were several issues playing together here, resulting in some packages never getting updated:
- The periodic package update was scheduling packages redundantly, combined with an update cycle that is nowadays longer than the anticipated 30 minutes, this resulted in the back part of the package list never being reached
- The secondary consequence was that the process crashed at some point with an assertion due to the update queue filling up, resulting in another possible reason for the package list to never be fully processed
- Packages were always inserted into the queue in the same order - now they are randomized, resulting in a natural robustness against similar issues
See also dlang/dub#2128 and #495.
> Ensure fair package updates and fix queue overflow

- dub.sdl
- dub.selections.json
- source/dubregistry/cache.d
- source/dubregistry/repositories/github.d
* adds a template URI parser for the Link header in GitHub (and also other parts) where it says it may use Hypermedia links in uritemplate.d - I will release this file as separate MIT library as well, so instead of including it here it might also be worth it just depending on it
* adds the possibility to cache headers in the urlcache module
* adds the readPagedList function in GitHub which traverses the list
For #456 to be properly fixed in this exact case right after deployment, either a new ETag must be sent by github (which is probably done on next release) or the db.urlcache.entries in vpmreg needs to be dropped by a DB administrator (s-ludwig) and all URLs should automatically be regrabbed. I think doing the latter will prevent some pain as cache may be cached for up to a year and …
> Fix #456: Missing tags when a project has more than 100 tags

- views/view_package.dt
This fixes that you need to keep reloading the cache to see updated documentation and allows you to view documentation of older versions.
> make dpldocs links versioned instead of master

- views/start.dt
Making it part of the string makes diet escape the special ampersand character. If we would insert raw HTML here we could introduce issues with HTML injection, so doing it the verbose way fixes it the easiest.
Might probably want to make this some global function instead of copy-pasting this code everywhere, but fixes the issue for now.
Fixes this on the start page:
> fix ellipse on start page not displaying properly

- views/view_package.dt
Always show custom documentation tab separately.
This makes it so that it's clear that the dpldocs link is most likely
just a code reference for all the code and the separate
documentation page that can be configured in the package config will be
shown as separate button.
Preview when custom documentation page is set:
Preview when custom documentation page is not set:
> rename documentation to reference

- README.md
github-username and password no longer exist for deployment!
See https://github.com/dlang/dub-registry/blob/a13c0b87efd5c59be2b9bfb58cebe604b2e8d2b1/source/app.d#L118
> fix README settings.json

- source/dubregistry/dbcontroller.d
Was looking at adding a migration myself, and obviously there is a bit of legacy that we can (and should) clean up first.
> dbcontroller: Remove old migration code

- dub.selections.json
- source/dubregistry/internal/workqueue.d
So that dub-registry compiles with the latest version of DMD.
> Upgrade submodules (vibe-d, vibe-core, eventcore, userman)

- README.md
> fix gitlab link in readme

- dub.sdl
- dub.selections.json
- source/dubregistry/cache.d
- source/dubregistry/dbcontroller.d
- source/dubregistry/mongodb.d
Diff is pretty simple. Tested locally with MongoDB v6.0.6 on Ubuntu 22.04.
Needs a new release of Vibe.d to work.
> Use latest version of MongoDB API for v5.1+ compatibility

- source/dubregistry/registry.d
keep quiet when it's just package not found, but otherwise log error
This will introduce logs for when DB requests fail, as well as when deserialization fails for some reason.
> add error logging on DB errors

- dub.selections.json
- source/app.d
- source/dubregistry/config.d
- source/dubregistry/dbcontroller.d
- source/dubregistry/repositories/bitbucket.d
- source/dubregistry/repositories/gitea.d
- source/dubregistry/repositories/github.d
- source/dubregistry/repositories/gitlab.d
- source/dubregistry/repositories/repository.d
- source/dubregistry/web.d
- views/my_packages.package.dt
Also Refactors the repository factory logic to enable proper matching of repository URLs to providers, so that local provider instances can be supported properly.
The `GiteaRepository` implementation is an adjusted version of `GithubRepository`, as the APIs are very similar.
> Add Gitea support

- source/dubregistry/dbcontroller.d
Instead of importing vibe.vibe, do more fine-grained imports.
> Reduce the scope of import in dubregistry.dbcontroller

- views/view_package.dt
DPLDocs no longer functions as a reference. This removes the link, it can be re-added if it starts working again in the future.
> Remove dpldocs link, it no longer functions.

- README.md
The endpoint actually returns everything as JSON,
which is an obvious DoS vector.
> Correct README instructions on how to run a mirror

- source/dubregistry/viewutils.d
This PR fixes the broken link that was pointing to an outdated URL for package scoring information.
- **File Updated:** `source/dubregistry/viewutils.d`
- **Old Link:**  
```
https://dub.pm/develop#package-scoring
```
- **New Link:**  
```
https://dub.pm/dub-guide/publishing/#package-scoring
```
- The updated link correctly points to the section explaining how package scores are computed.
**Reason for Change:**
- The old link resulted in a 404 error, leading to a broken user experience.
- This update ensures that users can now access the correct documentation.
**Related Issue:**
- Closes [[#85](https://github.com/dlang/dub-registry/issues/85)](https://github.com/dlang/dub-registry/issues/85) — Broken link to packages' scores.
> 🔗 Fixed broken link to package scoring in viewutils.d

- .github/workflows/test.yml
Ubuntu 20.04 LTS runner will be removed on 2025-04-15.
> CI: use ubuntu-22.04

- .github/workflows/test.yml
- dub.sdl
- dub.selections.json
- source/dubregistry/dbcontroller.d
- source/dubregistry/web.d
These are some improvements to the amount of GC allocations used during normal operation. The shallow package list and `updatePackageList` execution changes are new changes, since the other changes only helped temporarily.
See also: https://forum.dlang.org/thread/pnlyqzhuddbktbgyytxu@forum.dlang.org
> Reduce GC pressure to mitigate recent outages caused AI bots
