dlang/dub-registry

public/styles/common.css, source/app.d, views/home.dt, views/layout.dt
- refer to D (fixes Issue #80)
- better copy on front page
- small css changes for better alignment and spacing
=> improve page title

views/layout.dt
=> replace absolute link for the dub logo

source/dubregistry/web.d
- cache downloadInfo (now needs a restart when new files
are uploaded, but renders much faster)
=> provide LATEST dub version as download/LATEST

source/dubregistry/api.d, source/dubregistry/dbcontroller.d, source/dubregistry/registry.d
- add /api/packages/:name/latest         to get the latest version of a package
- add /api/packages/:name/info           to get info for a package (same as /packages/:name.json)
- add /api/packages/:name/:version/info  to get info for a package version (:version can be latest)
- add /api/packages/:name/stats          to get stats for a package
- add /api/packages/:name/:version/stats to get stats for a package version (:version can be latest)
=> REST interface for API

public/styles/common.css, source/dubregistry/viewutils.d, views/home.dt
Also adds a new "Added" column to make this scheme work. This looks a little bulky currently, any ideas for making that prettier (without too much work)?
=> Make table headers clickable for sorting.

source/dubregistry/api.d, source/dubregistry/dbcontroller.d, source/dubregistry/registry.d, source/dubregistry/viewutils.d, source/dubregistry/web.d, views/search_results.dt
- returns {name, description, latest_version} tuples
=> implement search API

views/home.dt
When hovering over the little icon left to the packages you can see what the icon means
=> Added tooltip for package categories in list

views/package_format_json.dt, views/package_format_sdl.dt
As explained in IRC by @s-ludwig
=> Mention "unittest" configuration special case

views/package_format_json.dt, views/package_format_sdl.dt
Accompanying PR for D-Programming-Language/dub#733
=> Mention the new "default" dependency attribute.

views/package_format_json.dt, views/package_format_sdl.dt
Resolves https://github.com/D-Programming-Language/dub-registry/issues/136.
=> Add NCSA license identifier

README.md, views/develop.dt, views/getting_started.dt, views/layout.dt
Updated links to our new namespace.
Be a bit careful - travis needs a trigger to know about the move.
=> update links to dlang

views/package_format_json.dt, views/package_format_sdl.dt
Add release-debug, release-nobounds and profile-gc build types to documentation.
=> Add release-debug, release-nobounds and profile-gc build types to documentation.

source/app.d, source/dubregistry/repositories/gitlab.d, source/dubregistry/repositories/repository.d, views/my_packages.package.dt, views/my_packages.register.dt, views/view_package.dt
This implements the GitLab portion of #117.
=> Add GitLab support

public/styles/common.css, source/app.d, source/dubregistry/registry.d, source/dubregistry/web.d, views/home.dt, views/view_package.dt
This is an intermediate step to improve loading performance and bandwidth use of the registry home page. This will later be replaced by different top ten lists.
=> Use pagination on the full package list

source/dubregistry/web.d
Server (code.dlang.org) crashes if you open [/?limit=0](https://code.dlang.org/?limit=0)
=> Fix potential server crash

public/styles/common.css, views/home.dt
=> Added Per Page option

views/view_package.dt
The link in the else scope may also be wrong but I couldn't find a package that uses it.
=> Fix wrong link to subpackage

public/styles/common.css
=> add a bit of margin between sidenav and top

public/styles/common.css
=> left align text in package info sidenav

public/styles/common.css, views/my_packages.register.dt, views/userman.login.dt
Same as #215 but for login page.
=> New layout of login page

views/userman.register.dt
Changes layout of the register page.
Screenshots:
=> New layout of the register page

public/styles/common.css
=> Fix alignment of top bar and page content.

public/styles/common.css, public/styles/top.css, public/styles/top_p.css
The previous PR #235 got accidentally pulled immediately, because of auto-merge and missing branch protection.
=> Really fix the top layout.

views/userman.profile.dt
Changes layout of the profile page.
=> New layout of the profile page

public/styles/common.css, views/my_packages.package.dt
=> New layout of the 'Edit package' page

public/styles/common.css, views/my_packages.dt
Replaces table with a list, so it is mobile-friendly and looks better.
Also, this is what search results page can look like, so any feedback is highly appreciated.
=> New layout of the "My packages" page

views/publish.dt
=> Mention GitLab and private registries in the docs.

source/dubregistry/dbcontroller.d, source/dubregistry/registry.d, source/dubregistry/viewutils.d, source/dubregistry/web.d, views/develop.dt, views/home.dt, views/search_results.dt, views/view_package.dt
- already affects search results
- we get no feedback/improvement ideas while score remains hidden
=> time to lift the curtains
=> time to display score

source/dubregistry/dbcontroller.d, source/dubregistry/registry.d
- more/better search results, but also more noise
=> index categories and readme for search

dub.sdl, dub.selections.json, source/app.d, source/dubregistry/api.d, source/dubregistry/cache.d, source/dubregistry/dbcontroller.d, source/dubregistry/internal/utils.d, source/dubregistry/internal/workqueue.d, source/dubregistry/mirror.d, source/dubregistry/notificationcenter.d, source/dubregistry/registry.d, source/dubregistry/repositories/bitbucket.d, source/dubregistry/repositories/github.d, source/dubregistry/repositories/gitlab.d, source/dubregistry/repositories/repository.d, source/dubregistry/scheduler.d, source/dubregistry/web.d
- Uses "safe" annotations more or less throughout the code base
- By using the latest vibe.d alpha, fixes MongoDB aggregations with MongoDB 3.6 series
- Fixes all errors and deprecation warnings
Fixes #282
=> Add safe annotations and upgrade to latest vibe.d pre-release.

dub.sdl
Lists the top-6 contributors:
https://github.com/dlang/dub-registry/graphs/contributors
=> Update authors list in package recipe.

source/app.d
I get tons of unrelated errors when I run the full registry for development locally.
Also it's nice for local development to update your "dev dump" deliberately and not every X minutes.
Moreover, my IP anonoymous quota of GitHub API queries get exceeded super fast, s.t. other services that depend on it don't work anymore.
There also seems to be an issue with the Vibe.d, because it sometimes gets unresponsive/blocks when updates failed.
=> Add --no-monitoring for local development

views/download.dt
=> Fix the download description for Arch Linux.

source/dubregistry/web.d
=> Check array length to avoid range violation errors

source/dubregistry/dbcontroller.d
=> Fix mixup of "bitbucket" and "gitlab" repository kinds.

source/dubregistry/internal/utils.d
The libevent driver doesn't support task joining across threads, so we are using std.concurrency to pass the results.
=> Make logo generation work for libevent.

netlify.sh, public/styles/common.css, source/dubregistry/web.d, views/start.dt
As we don't seem to make progress on that one, I hacked a "top10" front page together:
Desktop:
Mobile:
It's far from perfect, but I hope this gets the discussion started.
=> Add Top5 {most popular,created,update} front page

.gitignore, README.md
A start of a small developer guide.
=> Add the local settings.json to the .gitignore + improve README

.travis.yml, Dockerfile, README.md, docker-entrypoint.sh
CC @rracariu - this is based on your Docker image, I hope you're okay with using your work to set up such an automatic pipeline?
DockerHub:
https://hub.docker.com/r/dlangcommunity/dub-registry/
(will add explanation to the README once everything else is working)
=> Auto-deploy to Dockerhub

README.md, source/app.d, source/dubregistry/repositories/bitbucket.d
Adds support for private repositories on bitbucket.
=> Add support for bitbucket authentication

source/dubregistry/dbcontroller.d
- no longer allowed to insert _fts and _ftsx keys directly
- use cleaner createIndexes admin command instead
=> fix creation of FTS index with newer MongoDBs

categories.json
Example libraries in this category include Google's S2Geometry library (https://s2geometry.io/) and Uber's H3 library (https://github.com/uber/h3).
=> Add a new category for Geospacial libraries.

CONTRIBUTING.md
> > Please see [CONTRIBUTING.md](https://github.com/dlang/dub-registry/blob/master/CONTRIBUTING.md) for more information.
> 
> Thank you little @dlang-bot . Noticed now that dlang/dub-registry doesn't have a [CONTRIBUTING.md](https://github.com/dlang/dub-registry/blob/master/CONTRIBUTING.md) file! :smiley: 
This should guide some newbie contributors or, at least, not give a dead link from the bot message! :smile:
=> Add a simple and generic CONTRIBUTING.md file

source/dubregistry/dbcontroller.d
- see #93
- drop readme index (too much noise for MongoDB's simple search)
- search package name, categories, description, and authors
(with decreasing weights)
- fix unwanted indexing of other text-fields (`$**` key)
- fix indexing of authors
=> improve FTS index

README.md
continuation of #413 as I merged it myself with just one "resolved" review
=> Improve README wording for github token

public/styles/common.css, views/view_package.dt
**This PR shouldn't be merged until a new dub version is released with dlang/dub#1587.**
dlang/dub#1587 creates an `add` command that adds a dependency, so instead of copy/pasting `"vibe-d": "~>0.8.4"` you just have to run `dub add vibe-d`.
=> Use new `dub add` command instead of copying json/sdl

source/app.d
For the Heroku preview, let's use more than one package.
BTW the dummy user's credentials are `dummyuser` and `test1234`.
(this is run for every preview deployment)
=> Use more than one dummy repositories

source/dubregistry/viewutils.d, views/home.dt, views/search_results.dt, views/view_package.dt
=> fix broken link

dub.sdl, dub.selections.json
This allows us to get rid of a ton of deprecation warnings.
=> Upgrade to Vibe.d 0.8.5

source/dubregistry/web.d, views/my_packages.register.warn_fork.dt
=> fix fork registration regression

source/dubregistry/repositories/bitbucket.d
This upgrades the Bitbucket API support to API version 2.0 as API version 1.0 was removed from Bitbucket Cloud. This is intended to fix issue #444 
Beware of potential bugs in this code: I have tried to test the changes as much as possible inside a separate, cobbled together testbed, but I am unable to run rub-registry itself.
=> use bitbucket API 2.0

source/dubregistry/repositories/bitbucket.d
Added missing leading slashes in BitBucket API calls
=> Added missing leading slashes in BitBucket API calls

.travis.yml, dub.sdl, dub.selections.json
Because master is currently broken.
=> Upgrade dependencies to the latest releases & pin compiler version

dub.sdl, dub.selections.json, source/app.d, source/dubregistry/dbcontroller.d, source/dubregistry/web.d, views/dubregistry.mail.package-deprecation-warnings.dt, views/dubregistry.mail.package-version-errors.dt, views/home.dt, views/layout.dt, views/my_packages.dt, views/my_packages.package.dt, views/my_packages.register.dt, views/my_packages.register.warn_fork.dt, views/my_packages.remove.dt, views/search_results.dt, views/start.dt, views/userman.forgot_login.dt, views/userman.login.dt, views/userman.profile.dt, views/userman.register.dt, views/view_package.dt, views/view_package.versions.dt
Also upgrades to the latest vibe.d and UserMan versions to fix compiling with current frontend versions and fixes certificate related issues.
This change is required to make password reset e-mails work again, since the server running the registry has no local mail server anymore.
=> Custom mail settings and related changes

public/styles/common.css, views/view_package.dt
Implements #442.
Thanks to @WebFreak001 for helping me getting a local copy running (and making this PR possible).
=> Bring back copy&paste dependency boxes

dub.selections.json, source/app.d, source/dubregistry/cache.d, source/dubregistry/repositories/github.d, source/dubregistry/repositories/repository.d
Uses authorization tokens instead of the password for accessing the GitHub API.
=> Fix GitHub API authenthication

public/opensearch.xml, views/layout.dt
This allows to search dub packages easier from address bar in browsers.
=> Add OpenSearch description

source/app.d, source/dubregistry/internal/utils.d, source/dubregistry/web.d, views/my_packages.dt, views/my_packages.package.dt
Getting the registry to work on a modern workstation is going to be a lot of work:
- Tons of deprecations in dependencies;
- MongoDB broken;
- Tons of deprecations inside the code itself;
This addresses some low-hanging fruits.
=> Clean up some more deprecations

dub.selections.json, source/app.d, source/dubregistry/dbcontroller.d, source/dubregistry/internal/utils.d, source/dubregistry/internal/workqueue.d, source/dubregistry/registry.d
Fixes all compile errors without actually upgrading for now.
=> Preparations for vibe-core 2 compatibility

source/dubregistry/registry.d, source/dubregistry/web.d
To accomodate for the latest round of deprecations.
=> Replace usages of in ref with const ref

dub.selections.json, source/dubregistry/dbcontroller.d
=> Upgrade and improve error message

dub.selections.json
Fixes #574 by upgrading to userman 0.4.4.
=> Upgrade dependencies

README.md
=> Remove unmaintained staging server link

views/userman.register.dt
=> Add missing registration form field required for the latest userman
